# Dockerfile - Frontend (React Application)

# 1. Imagem base do Node.js
FROM node:24.1
ENV NODE_VERSION 24.1.0

WORKDIR /frontend

RUN npm install -g npm@11.4.1

COPY package*.json ./
RUN npm install

COPY . /frontend/

RUN npm run build
